name: Build Tailscale OpenWrt Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release'
        required: true
        default: true
        type: boolean
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: false
        default: ''

env:
  GO_VERSION: '1.21'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Install UPX
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl
        
    - name: Verify dependencies
      run: |
        go version
        upx --version
        git --version
        
    - name: Build binaries
      run: |
        ./build-tailscale-openwrt.sh
        
    - name: Prepare release artifacts
      run: |
        mkdir -p release-artifacts
        cd binaries
        
        # Create individual archives for each binary
        for binary in tailscale-*; do
          if [ -f "$binary" ]; then
            echo "Preparing $binary..."
            arch=$(echo "$binary" | sed 's/tailscale-//')
            
            # Create archive with binary and info
            mkdir -p "tailscale-openwrt-$arch"
            cp "$binary" "tailscale-openwrt-$arch/tailscale"
            
            # Create installation script
            {
              echo '#!/bin/sh'
              echo '# Tailscale OpenWrt Installation Script'
              echo 'set -e'
              echo ''
              echo 'BINARY_NAME="tailscale"'
              echo 'INSTALL_PATH="/usr/bin"'
              echo ''
              echo 'echo "Installing Tailscale for OpenWrt..."'
              echo ''
              echo '# Make binary executable'
              echo 'chmod +x "$BINARY_NAME"'
              echo ''
              echo '# Copy to system path'
              echo 'cp "$BINARY_NAME" "$INSTALL_PATH/$BINARY_NAME"'
              echo 'ln -sf "$INSTALL_PATH/$BINARY_NAME" "$INSTALL_PATH/tailscaled"'
              echo ''
              echo 'echo "Tailscale installed successfully!"'
              echo 'echo ""'
              echo 'echo "Usage:"'
              echo 'echo "  tailscale up --authkey=YOUR_AUTH_KEY"'
              echo 'echo "  tailscale status"'
              echo 'echo ""'
              echo 'echo "For more information, visit: https://tailscale.com/kb/1188/openwrt"'
            } > "tailscale-openwrt-$arch/install.sh"
            
            chmod +x "tailscale-openwrt-$arch/install.sh"
            
            # Create README
            {
              echo "# Tailscale for OpenWrt ($arch)"
              echo ""
              echo "This package contains a minimized Tailscale binary built specifically for OpenWrt devices."
              echo ""
              echo "## Architecture"
              echo "- **Target**: $arch"
              echo "- **Binary Size**: \$(ls -lh $binary | awk '{print \$5}')"
              echo "- **Features**: Combined tailscale + tailscaled functionality"
              echo ""
              echo "## Installation"
              echo ""
              echo "1. Extract this archive to your OpenWrt device"
              echo "2. Run the installation script:"
              echo "   \`\`\`bash"
              echo "   chmod +x install.sh"
              echo "   ./install.sh"
              echo "   \`\`\`"
              echo ""
              echo "## Usage"
              echo ""
              echo "1. Start Tailscale:"
              echo "   \`\`\`bash"
              echo "   tailscale up --authkey=YOUR_AUTH_KEY"
              echo "   \`\`\`"
              echo ""
              echo "2. Check status:"
              echo "   \`\`\`bash"
              echo "   tailscale status"
              echo "   \`\`\`"
              echo ""
              echo "## Binary Information"
              echo ""
              echo "- **Static linking**: No external dependencies required"
              echo "- **Size optimized**: Debug symbols stripped, UPX compressed"
              echo "- **Combined binary**: Single executable handles both client and daemon functions"
              echo ""
              echo "## Support"
              echo ""
              echo "For issues and documentation, visit:"
              echo "- [Tailscale OpenWrt Guide](https://tailscale.com/kb/1188/openwrt)"
              echo "- [Tailscale Community](https://github.com/tailscale/tailscale/discussions)"
            } > "tailscale-openwrt-$arch/README.md"
            
            # Create tar.gz archive
            tar -czf "../release-artifacts/tailscale-openwrt-$arch.tar.gz" "tailscale-openwrt-$arch"
            
            # Create zip archive
            zip -r "../release-artifacts/tailscale-openwrt-$arch.zip" "tailscale-openwrt-$arch"
            
            # Also create a standalone binary with proper extension
            cp "$binary" "../release-artifacts/tailscale-$arch.bin"
            
            # Cleanup
            rm -rf "tailscale-openwrt-$arch"
          fi
        done
        
    - name: Generate release notes
      run: |
        cd binaries
        echo "# Tailscale OpenWrt Builds" > ../release-notes.md
        echo "" >> ../release-notes.md
        echo "Minimized Tailscale binaries for OpenWrt devices across multiple architectures." >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "## Built Binaries" >> ../release-notes.md
        echo "" >> ../release-notes.md
        
        for binary in tailscale-*; do
          if [ -f "$binary" ]; then
            arch=$(echo "$binary" | sed 's/tailscale-//')
            size=$(ls -lh "$binary" | awk '{print $5}')
            echo "- **$arch**: $size" >> ../release-notes.md
          fi
        done
        
        echo "" >> ../release-notes.md
        echo "## Installation" >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "1. Download the appropriate archive for your device architecture:" >> ../release-notes.md
        echo "   - **ZIP format**: \`tailscale-openwrt-[arch].zip\` (Windows/cross-platform)" >> ../release-notes.md
        echo "   - **TAR.GZ format**: \`tailscale-openwrt-[arch].tar.gz\` (Linux/Unix)" >> ../release-notes.md
        echo "   - **Standalone binary**: \`tailscale-[arch].bin\` (direct download)" >> ../release-notes.md
        echo "2. Extract and run the included installation script" >> ../release-notes.md
        echo "3. Follow the usage instructions in the README" >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "## Supported Architectures" >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "- **armv7**: 32-bit ARM with hardware floating point (most modern ARM routers)" >> ../release-notes.md
        echo "- **arm64**: 64-bit ARM (newer high-end routers)" >> ../release-notes.md
        echo "- **mips**: 32-bit MIPS big-endian with software floating point (older routers)" >> ../release-notes.md
        echo "- **mipsle**: 32-bit MIPS little-endian with software floating point (some older routers)" >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "## Build Information" >> ../release-notes.md
        echo "" >> ../release-notes.md
        echo "- **Built from**: [Tailscale upstream](https://github.com/tailscale/tailscale)" >> ../release-notes.md
        echo "- **Go Version**: $(go version | awk '{print $3}')" >> ../release-notes.md
        echo "- **Build Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> ../release-notes.md
        echo "- **Optimizations**: Symbol stripping, UPX compression, static linking" >> ../release-notes.md
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tailscale-openwrt-binaries
        path: |
          release-artifacts/
          release-notes.md
        retention-days: 30
        
    - name: Determine release tag
      id: release_tag
      run: |
        if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        elif [ -n "${{ github.event.inputs.tag_name }}" ]; then
          echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag_name=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      if: github.event_name == 'push' || github.event.inputs.create_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_tag.outputs.tag_name }}
        name: "Tailscale OpenWrt Builds ${{ steps.release_tag.outputs.tag_name }}"
        body_path: release-notes.md
        files: |
          release-artifacts/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}